name: check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting with prettier
        uses: creyD/prettier_action@v4.6
        with:
          no_commit: true
          prettier_options: --check **/*.{yml,md}
  seo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - run: pip install .
      - run: python -m unittest discover -s tests
      - run: zensical build -f zensical.toml
